# Generated by Django 5.2 on 2025-04-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20250405_0520'),
        ('listings', '0004_college_sponsor'),
    ]

    operations = [
    ]
