# Generated by Django 5.2 on 2025-04-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_merge_0004_auto_20250405_0520_0004_college_sponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegesponsorshiphistory',
            name='college',
        ),
        migrations.RemoveField(
            model_name='collegesponsorshiphistory',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='eventrequest',
            name='college',
        ),
        migrations.RemoveField(
            model_name='eventrequest',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='sponsorevent',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='sponsorhistory',
            name='college',
        ),
        migrations.RemoveField(
            model_name='sponsorhistory',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='college',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='id',
        ),
        migrations.AddField(
            model_name='college',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='college_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsor_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='state',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientlisting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='college',
            name='state',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsorlisting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='CollegeEvent',
        ),
        migrations.DeleteModel(
            name='CollegeSponsorshipHistory',
        ),
        migrations.DeleteModel(
            name='EventRequest',
        ),
        migrations.DeleteModel(
            name='SponsorEvent',
        ),
        migrations.DeleteModel(
            name='SponsorHistory',
        ),
    ]
